# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Kedua.ui'
#
# Created: Mon Dec 17 12:06:19 2018
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow2(object):
    def setup2(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(778, 601)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_signing = QtGui.QFrame(self.frame)
        self.frame_signing.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_signing.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_signing.setObjectName(_fromUtf8("frame_signing"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_signing)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.signing = QtGui.QLabel(self.frame_signing)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.signing.setFont(font)
        self.signing.setStyleSheet(_fromUtf8("background-color: rgb(255, 166, 77);\n"
"color: rgb(255, 255, 255);"))
        self.signing.setScaledContents(False)
        self.signing.setMargin(10)
        self.signing.setObjectName(_fromUtf8("signing"))
        self.verticalLayout_5.addWidget(self.signing)
        self.scrollArea = QtGui.QScrollArea(self.frame_signing)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 456, 271))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frame_m = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m.setStyleSheet(_fromUtf8(""))
        self.frame_m.setFrameShape(QtGui.QFrame.Box)
        self.frame_m.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m.setObjectName(_fromUtf8("frame_m"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_m)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_m = QtGui.QLabel(self.frame_m)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_m.setFont(font)
        self.label_m.setAutoFillBackground(False)
        self.label_m.setStyleSheet(_fromUtf8(""))
        self.label_m.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m.setWordWrap(False)
        self.label_m.setObjectName(_fromUtf8("label_m"))
        self.gridLayout_7.addWidget(self.label_m, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_m)
        self.frame_x = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_x.setFrameShape(QtGui.QFrame.Box)
        self.frame_x.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_x.setObjectName(_fromUtf8("frame_x"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_x)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_x = QtGui.QLabel(self.frame_x)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_x.setFont(font)
        self.label_x.setAutoFillBackground(False)
        self.label_x.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x.setWordWrap(False)
        self.label_x.setObjectName(_fromUtf8("label_x"))
        self.gridLayout_8.addWidget(self.label_x, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_x)
        self.frame_k = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_k.setFrameShape(QtGui.QFrame.Box)
        self.frame_k.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_k.setObjectName(_fromUtf8("frame_k"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_k)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_k = QtGui.QLabel(self.frame_k)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k.setFont(font)
        self.label_k.setAutoFillBackground(False)
        self.label_k.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k.setWordWrap(False)
        self.label_k.setObjectName(_fromUtf8("label_k"))
        self.gridLayout_9.addWidget(self.label_k, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_k)
        self.frame_q = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_q.setStyleSheet(_fromUtf8("background-color: rgb(158,158,158);"))
        self.frame_q.setFrameShape(QtGui.QFrame.Box)
        self.frame_q.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_q.setObjectName(_fromUtf8("frame_q"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_q)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_p = QtGui.QLabel(self.frame_q)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_p.setFont(font)
        self.label_p.setAutoFillBackground(False)
        self.label_p.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_p.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p.setWordWrap(False)
        self.label_p.setObjectName(_fromUtf8("label_p"))
        self.gridLayout_10.addWidget(self.label_p, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_q)
        self.frame_p = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_p.setFrameShape(QtGui.QFrame.Box)
        self.frame_p.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_p.setObjectName(_fromUtf8("frame_p"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_p)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_q = QtGui.QLabel(self.frame_p)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q.setFont(font)
        self.label_q.setAutoFillBackground(False)
        self.label_q.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q.setWordWrap(False)
        self.label_q.setObjectName(_fromUtf8("label_q"))
        self.gridLayout_11.addWidget(self.label_q, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_p)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_pic = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_pic.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic.setFont(font)
        self.label_pic.setAutoFillBackground(False)
        self.label_pic.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic.setWordWrap(False)
        self.label_pic.setObjectName(_fromUtf8("label_pic"))
        self.horizontalLayout_6.addWidget(self.label_pic)
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setText(_fromUtf8(""))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_6.addWidget(self.label)
        self.label_k_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_2.setFont(font)
        self.label_k_2.setAutoFillBackground(False)
        self.label_k_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_2.setText(_fromUtf8(""))
        self.label_k_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_2.setWordWrap(False)
        self.label_k_2.setObjectName(_fromUtf8("label_k_2"))
        self.horizontalLayout_6.addWidget(self.label_k_2)
        self.label_pic_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_3.setFont(font)
        self.label_pic_3.setAutoFillBackground(False)
        self.label_pic_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_3.setText(_fromUtf8(""))
        self.label_pic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_3.setWordWrap(False)
        self.label_pic_3.setObjectName(_fromUtf8("label_pic_3"))
        self.horizontalLayout_6.addWidget(self.label_pic_3)
        self.label_q_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_2.setFont(font)
        self.label_q_2.setAutoFillBackground(False)
        self.label_q_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_2.setText(_fromUtf8(""))
        self.label_q_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_2.setWordWrap(False)
        self.label_q_2.setObjectName(_fromUtf8("label_q_2"))
        self.horizontalLayout_6.addWidget(self.label_q_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.frame_m_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_2.setStyleSheet(_fromUtf8(""))
        self.frame_m_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_2.setObjectName(_fromUtf8("frame_m_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_m_2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_hash = QtGui.QLabel(self.frame_m_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_hash.setFont(font)
        self.label_hash.setAutoFillBackground(False)
        self.label_hash.setStyleSheet(_fromUtf8(""))
        self.label_hash.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_hash.setText(_fromUtf8(""))
        self.label_hash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hash.setWordWrap(False)
        self.label_hash.setObjectName(_fromUtf8("label_hash"))
        self.gridLayout_12.addWidget(self.label_hash, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_m_2)
        self.label_x_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_x_2.setFont(font)
        self.label_x_2.setAutoFillBackground(False)
        self.label_x_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_x_2.setText(_fromUtf8(""))
        self.label_x_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x_2.setWordWrap(False)
        self.label_x_2.setObjectName(_fromUtf8("label_x_2"))
        self.horizontalLayout_7.addWidget(self.label_x_2)
        self.label_k_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_3.setFont(font)
        self.label_k_3.setAutoFillBackground(False)
        self.label_k_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_3.setText(_fromUtf8(""))
        self.label_k_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_3.setWordWrap(False)
        self.label_k_3.setObjectName(_fromUtf8("label_k_3"))
        self.horizontalLayout_7.addWidget(self.label_k_3)
        self.frame_m_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_5.setStyleSheet(_fromUtf8(""))
        self.frame_m_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_5.setObjectName(_fromUtf8("frame_m_5"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_m_5)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_nilaiL = QtGui.QLabel(self.frame_m_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_nilaiL.setFont(font)
        self.label_nilaiL.setAutoFillBackground(False)
        self.label_nilaiL.setStyleSheet(_fromUtf8(""))
        self.label_nilaiL.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaiL.setText(_fromUtf8(""))
        self.label_nilaiL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaiL.setWordWrap(False)
        self.label_nilaiL.setObjectName(_fromUtf8("label_nilaiL"))
        self.gridLayout_15.addWidget(self.label_nilaiL, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_m_5)
        self.label_q_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_3.setFont(font)
        self.label_q_3.setAutoFillBackground(False)
        self.label_q_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_3.setText(_fromUtf8(""))
        self.label_q_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_3.setWordWrap(False)
        self.label_q_3.setObjectName(_fromUtf8("label_q_3"))
        self.horizontalLayout_7.addWidget(self.label_q_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_pic_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_pic_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_2.setFont(font)
        self.label_pic_2.setAutoFillBackground(False)
        self.label_pic_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_2.setWordWrap(False)
        self.label_pic_2.setObjectName(_fromUtf8("label_pic_2"))
        self.horizontalLayout_8.addWidget(self.label_pic_2)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.label_k_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_4.setFont(font)
        self.label_k_4.setAutoFillBackground(False)
        self.label_k_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_4.setText(_fromUtf8(""))
        self.label_k_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_4.setWordWrap(False)
        self.label_k_4.setObjectName(_fromUtf8("label_k_4"))
        self.horizontalLayout_8.addWidget(self.label_k_4)
        self.label_pic_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_4.setFont(font)
        self.label_pic_4.setAutoFillBackground(False)
        self.label_pic_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_4.setText(_fromUtf8(""))
        self.label_pic_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_4.setWordWrap(False)
        self.label_pic_4.setObjectName(_fromUtf8("label_pic_4"))
        self.horizontalLayout_8.addWidget(self.label_pic_4)
        self.label_q_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_4.setFont(font)
        self.label_q_4.setAutoFillBackground(False)
        self.label_q_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_4.setText(_fromUtf8(""))
        self.label_q_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_4.setWordWrap(False)
        self.label_q_4.setObjectName(_fromUtf8("label_q_4"))
        self.horizontalLayout_8.addWidget(self.label_q_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.frame_m_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_3.setStyleSheet(_fromUtf8(""))
        self.frame_m_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_3.setObjectName(_fromUtf8("frame_m_3"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_m_3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_nilaihash = QtGui.QLabel(self.frame_m_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilaihash.setFont(font)
        self.label_nilaihash.setAutoFillBackground(False)
        self.label_nilaihash.setStyleSheet(_fromUtf8(""))
        self.label_nilaihash.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaihash.setText(_fromUtf8(""))
        self.label_nilaihash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaihash.setWordWrap(False)
        self.label_nilaihash.setObjectName(_fromUtf8("label_nilaihash"))
        self.gridLayout_13.addWidget(self.label_nilaihash, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_m_3)
        self.label_x_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_x_3.setFont(font)
        self.label_x_3.setAutoFillBackground(False)
        self.label_x_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_x_3.setText(_fromUtf8(""))
        self.label_x_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x_3.setWordWrap(False)
        self.label_x_3.setObjectName(_fromUtf8("label_x_3"))
        self.horizontalLayout_9.addWidget(self.label_x_3)
        self.label_k_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_5.setFont(font)
        self.label_k_5.setAutoFillBackground(False)
        self.label_k_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_5.setText(_fromUtf8(""))
        self.label_k_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_5.setWordWrap(False)
        self.label_k_5.setObjectName(_fromUtf8("label_k_5"))
        self.horizontalLayout_9.addWidget(self.label_k_5)
        self.frame_m_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_4.setStyleSheet(_fromUtf8(""))
        self.frame_m_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_4.setObjectName(_fromUtf8("frame_m_4"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frame_m_4)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_nilaip = QtGui.QLabel(self.frame_m_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilaip.setFont(font)
        self.label_nilaip.setAutoFillBackground(False)
        self.label_nilaip.setStyleSheet(_fromUtf8(""))
        self.label_nilaip.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaip.setText(_fromUtf8(""))
        self.label_nilaip.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaip.setWordWrap(False)
        self.label_nilaip.setObjectName(_fromUtf8("label_nilaip"))
        self.gridLayout_14.addWidget(self.label_nilaip, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_m_4)
        self.label_q_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_5.setFont(font)
        self.label_q_5.setAutoFillBackground(False)
        self.label_q_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_5.setText(_fromUtf8(""))
        self.label_q_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_5.setWordWrap(False)
        self.label_q_5.setObjectName(_fromUtf8("label_q_5"))
        self.horizontalLayout_9.addWidget(self.label_q_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_signing)
        self.frame_output = QtGui.QFrame(self.frame)
        self.frame_output.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_output.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_output.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_output.setObjectName(_fromUtf8("frame_output"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_output)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.note = QtGui.QLabel(self.frame_output)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.note.setFont(font)
        self.note.setStyleSheet(_fromUtf8("background-color: rgb(255, 166, 77);\n"
"color: rgb(255, 255, 255);"))
        self.note.setMargin(10)
        self.note.setObjectName(_fromUtf8("note"))
        self.verticalLayout.addWidget(self.note)
        self.isi_note = QtGui.QTextBrowser(self.frame_output)
        self.isi_note.setObjectName(_fromUtf8("isi_note"))
        self.verticalLayout.addWidget(self.isi_note)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.output = QtGui.QLabel(self.frame_output)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setStyleSheet(_fromUtf8("background-color: rgb(255, 166, 77);\n"
"color: rgb(255, 255, 255);"))
        self.output.setMargin(10)
        self.output.setObjectName(_fromUtf8("output"))
        self.verticalLayout_4.addWidget(self.output)
        self.nilai_output = QtGui.QTextBrowser(self.frame_output)
        self.nilai_output.setObjectName(_fromUtf8("nilai_output"))
        self.verticalLayout_4.addWidget(self.nilai_output)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_output)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.frame_input = QtGui.QFrame(self.frame)
        self.frame_input.setMaximumSize(QtCore.QSize(280, 16777215))
        self.frame_input.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_input.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_input.setObjectName(_fromUtf8("frame_input"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_input)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_judul = QtGui.QLabel(self.frame_input)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_judul.setFont(font)
        self.label_judul.setStyleSheet(_fromUtf8("color: rgb(255, 166, 77);"))
        self.label_judul.setAlignment(QtCore.Qt.AlignCenter)
        self.label_judul.setWordWrap(True)
        self.label_judul.setMargin(10)
        self.label_judul.setObjectName(_fromUtf8("label_judul"))
        self.verticalLayout_7.addWidget(self.label_judul)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_5 = QtGui.QLabel(self.frame_input)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_2.addWidget(self.label_5)
        self.box_nilaiL = QtGui.QComboBox(self.frame_input)
        self.box_nilaiL.setObjectName(_fromUtf8("box_nilaiL"))
        self.box_nilaiL.addItem(_fromUtf8(""))
        self.box_nilaiL.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.box_nilaiL)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_ok = QtGui.QPushButton(self.frame_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.horizontalLayout_2.addWidget(self.btn_ok)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.btn_next = QtGui.QPushButton(self.frame_input)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_next.setFont(font)
        self.btn_next.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.btn_next.setText(_fromUtf8(""))
        self.btn_next.setAutoDefault(False)
        self.btn_next.setDefault(False)
        self.btn_next.setFlat(True)
        self.btn_next.setObjectName(_fromUtf8("btn_next"))
        self.horizontalLayout_4.addWidget(self.btn_next)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_input)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Digital Signature", None))
        self.signing.setText(_translate("MainWindow", "SIGNING", None))
        self.label_m.setText(_translate("MainWindow", "M", None))
        self.label_x.setText(_translate("MainWindow", "x", None))
        self.label_k.setText(_translate("MainWindow", "k", None))
        self.label_p.setText(_translate("MainWindow", "p", None))
        self.label_q.setText(_translate("MainWindow", "q", None))
        self.label_pic.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_pic_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.note.setText(_translate("MainWindow", "NOTE", None))
        self.isi_note.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">=== Bilangan Prima (p) === </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Salah satu input untuk membuat global public-key</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Komputasi:<span style=\" font-weight:600;\">  </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">2^(L-1) &lt; P &lt; 2^L </span></p>\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">=== L === </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Input untuk mencari bilangan prima</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Komputasi:<span style=\" font-weight:600;\"> </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">512 &lt;= L &lt;= 1024 | L = Kelipatan 64 </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">*Pada kasus ini diubah menjadi</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">32 &lt;= L &lt;= 64 | L = Kelipatan 2</span></p></body></html>", None))
        self.output.setText(_translate("MainWindow", "OUTPUT", None))
        self.label_judul.setText(_translate("MainWindow", "Mencari Bilangan Prima", None))
        self.label_5.setText(_translate("MainWindow", "Pilih nilai L", None))
        self.box_nilaiL.setItemText(0, _translate("MainWindow", "32", None))
        self.box_nilaiL.setItemText(1, _translate("MainWindow", "64", None))
        self.btn_ok.setText(_translate("MainWindow", "OK", None))


