# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ketujuh.ui'
#
# Created: Wed Jan 16 19:45:01 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow7(object):
    def setup7(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(778, 601)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_signing = QtGui.QFrame(self.frame)
        self.frame_signing.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_signing.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_signing.setObjectName(_fromUtf8("frame_signing"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_signing)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.signing = QtGui.QLabel(self.frame_signing)
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.signing.setFont(font)
        self.signing.setStyleSheet(_fromUtf8("background-color: rgb(255, 166, 77);\n"
"color: rgb(255, 255, 255);"))
        self.signing.setScaledContents(False)
        self.signing.setMargin(10)
        self.signing.setObjectName(_fromUtf8("signing"))
        self.verticalLayout_5.addWidget(self.signing)
        self.scrollArea = QtGui.QScrollArea(self.frame_signing)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 481, 1027))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.frame_m = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m.setStyleSheet(_fromUtf8(""))
        self.frame_m.setFrameShape(QtGui.QFrame.Box)
        self.frame_m.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m.setObjectName(_fromUtf8("frame_m"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_m)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_m = QtGui.QLabel(self.frame_m)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_m.setFont(font)
        self.label_m.setAutoFillBackground(False)
        self.label_m.setStyleSheet(_fromUtf8(""))
        self.label_m.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_m.setAlignment(QtCore.Qt.AlignCenter)
        self.label_m.setWordWrap(False)
        self.label_m.setObjectName(_fromUtf8("label_m"))
        self.gridLayout_7.addWidget(self.label_m, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_m)
        self.frame_x = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_x.setStyleSheet(_fromUtf8(""))
        self.frame_x.setFrameShape(QtGui.QFrame.Box)
        self.frame_x.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_x.setObjectName(_fromUtf8("frame_x"))
        self.gridLayout_8 = QtGui.QGridLayout(self.frame_x)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_x = QtGui.QLabel(self.frame_x)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_x.setFont(font)
        self.label_x.setAutoFillBackground(False)
        self.label_x.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_x.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x.setWordWrap(False)
        self.label_x.setObjectName(_fromUtf8("label_x"))
        self.gridLayout_8.addWidget(self.label_x, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_x)
        self.frame_k = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_k.setStyleSheet(_fromUtf8(""))
        self.frame_k.setFrameShape(QtGui.QFrame.Box)
        self.frame_k.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_k.setObjectName(_fromUtf8("frame_k"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame_k)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_k = QtGui.QLabel(self.frame_k)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k.setFont(font)
        self.label_k.setAutoFillBackground(False)
        self.label_k.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k.setWordWrap(False)
        self.label_k.setObjectName(_fromUtf8("label_k"))
        self.gridLayout_9.addWidget(self.label_k, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_k)
        self.frame_q = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_q.setStyleSheet(_fromUtf8(""))
        self.frame_q.setFrameShape(QtGui.QFrame.Box)
        self.frame_q.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_q.setObjectName(_fromUtf8("frame_q"))
        self.gridLayout_10 = QtGui.QGridLayout(self.frame_q)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_p = QtGui.QLabel(self.frame_q)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_p.setFont(font)
        self.label_p.setAutoFillBackground(False)
        self.label_p.setStyleSheet(_fromUtf8(""))
        self.label_p.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_p.setWordWrap(False)
        self.label_p.setObjectName(_fromUtf8("label_p"))
        self.gridLayout_10.addWidget(self.label_p, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_q)
        self.frame_p = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_p.setStyleSheet(_fromUtf8(""))
        self.frame_p.setFrameShape(QtGui.QFrame.Box)
        self.frame_p.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_p.setObjectName(_fromUtf8("frame_p"))
        self.gridLayout_11 = QtGui.QGridLayout(self.frame_p)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_q = QtGui.QLabel(self.frame_p)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q.setFont(font)
        self.label_q.setAutoFillBackground(False)
        self.label_q.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q.setWordWrap(False)
        self.label_q.setObjectName(_fromUtf8("label_q"))
        self.gridLayout_11.addWidget(self.label_q, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_p)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_pic = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_pic.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic.setFont(font)
        self.label_pic.setAutoFillBackground(False)
        self.label_pic.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic.setWordWrap(False)
        self.label_pic.setObjectName(_fromUtf8("label_pic"))
        self.horizontalLayout_6.addWidget(self.label_pic)
        self.label_pic_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_pic_7.setText(_fromUtf8(""))
        self.label_pic_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_7.setObjectName(_fromUtf8("label_pic_7"))
        self.horizontalLayout_6.addWidget(self.label_pic_7)
        self.label_pic_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_6.setFont(font)
        self.label_pic_6.setAutoFillBackground(False)
        self.label_pic_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_6.setText(_fromUtf8(""))
        self.label_pic_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_6.setWordWrap(False)
        self.label_pic_6.setObjectName(_fromUtf8("label_pic_6"))
        self.horizontalLayout_6.addWidget(self.label_pic_6)
        self.label_pic_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_3.setFont(font)
        self.label_pic_3.setAutoFillBackground(False)
        self.label_pic_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_3.setText(_fromUtf8(""))
        self.label_pic_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_3.setWordWrap(False)
        self.label_pic_3.setObjectName(_fromUtf8("label_pic_3"))
        self.horizontalLayout_6.addWidget(self.label_pic_3)
        self.label_pic_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_4.setFont(font)
        self.label_pic_4.setAutoFillBackground(False)
        self.label_pic_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_4.setText(_fromUtf8(""))
        self.label_pic_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_4.setWordWrap(False)
        self.label_pic_4.setObjectName(_fromUtf8("label_pic_4"))
        self.horizontalLayout_6.addWidget(self.label_pic_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.frame_m_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_2.setStyleSheet(_fromUtf8(""))
        self.frame_m_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_2.setObjectName(_fromUtf8("frame_m_2"))
        self.gridLayout_12 = QtGui.QGridLayout(self.frame_m_2)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.label_hash = QtGui.QLabel(self.frame_m_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_hash.setFont(font)
        self.label_hash.setAutoFillBackground(False)
        self.label_hash.setStyleSheet(_fromUtf8(""))
        self.label_hash.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_hash.setText(_fromUtf8(""))
        self.label_hash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_hash.setWordWrap(False)
        self.label_hash.setObjectName(_fromUtf8("label_hash"))
        self.gridLayout_12.addWidget(self.label_hash, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_m_2)
        self.frame_m_7 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_7.setStyleSheet(_fromUtf8("background-color: rgb(224,224,224);"))
        self.frame_m_7.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_7.setObjectName(_fromUtf8("frame_m_7"))
        self.gridLayout_17 = QtGui.QGridLayout(self.frame_m_7)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.label_nilaix = QtGui.QLabel(self.frame_m_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilaix.setFont(font)
        self.label_nilaix.setAutoFillBackground(False)
        self.label_nilaix.setStyleSheet(_fromUtf8(""))
        self.label_nilaix.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaix.setText(_fromUtf8(""))
        self.label_nilaix.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaix.setWordWrap(False)
        self.label_nilaix.setObjectName(_fromUtf8("label_nilaix"))
        self.gridLayout_17.addWidget(self.label_nilaix, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_m_7)
        self.frame_m_6 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_6.setStyleSheet(_fromUtf8("background-color: rgb(224,224,224);"))
        self.frame_m_6.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_6.setObjectName(_fromUtf8("frame_m_6"))
        self.gridLayout_16 = QtGui.QGridLayout(self.frame_m_6)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.label_nilaik = QtGui.QLabel(self.frame_m_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilaik.setFont(font)
        self.label_nilaik.setAutoFillBackground(False)
        self.label_nilaik.setStyleSheet(_fromUtf8(""))
        self.label_nilaik.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaik.setText(_fromUtf8(""))
        self.label_nilaik.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaik.setWordWrap(False)
        self.label_nilaik.setObjectName(_fromUtf8("label_nilaik"))
        self.gridLayout_16.addWidget(self.label_nilaik, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_m_6)
        self.frame_m_8 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_8.setStyleSheet(_fromUtf8(""))
        self.frame_m_8.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_8.setObjectName(_fromUtf8("frame_m_8"))
        self.gridLayout_18 = QtGui.QGridLayout(self.frame_m_8)
        self.gridLayout_18.setObjectName(_fromUtf8("gridLayout_18"))
        self.label_nilaiL = QtGui.QLabel(self.frame_m_8)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_nilaiL.setFont(font)
        self.label_nilaiL.setAutoFillBackground(False)
        self.label_nilaiL.setStyleSheet(_fromUtf8(""))
        self.label_nilaiL.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaiL.setText(_fromUtf8(""))
        self.label_nilaiL.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaiL.setWordWrap(False)
        self.label_nilaiL.setObjectName(_fromUtf8("label_nilaiL"))
        self.gridLayout_18.addWidget(self.label_nilaiL, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_m_8)
        self.frame_m_5 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_5.setStyleSheet(_fromUtf8("background-color: rgb(224,224,224);"))
        self.frame_m_5.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_5.setObjectName(_fromUtf8("frame_m_5"))
        self.gridLayout_15 = QtGui.QGridLayout(self.frame_m_5)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.label_nilaiq = QtGui.QLabel(self.frame_m_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilaiq.setFont(font)
        self.label_nilaiq.setAutoFillBackground(False)
        self.label_nilaiq.setStyleSheet(_fromUtf8(""))
        self.label_nilaiq.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaiq.setText(_fromUtf8(""))
        self.label_nilaiq.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaiq.setWordWrap(False)
        self.label_nilaiq.setObjectName(_fromUtf8("label_nilaiq"))
        self.gridLayout_15.addWidget(self.label_nilaiq, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_m_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_pic_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_pic_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_2.setFont(font)
        self.label_pic_2.setAutoFillBackground(False)
        self.label_pic_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_2.setWordWrap(False)
        self.label_pic_2.setObjectName(_fromUtf8("label_pic_2"))
        self.horizontalLayout_8.addWidget(self.label_pic_2)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_8.addWidget(self.label_2)
        self.label_k_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_4.setFont(font)
        self.label_k_4.setAutoFillBackground(False)
        self.label_k_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_4.setText(_fromUtf8(""))
        self.label_k_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_4.setWordWrap(False)
        self.label_k_4.setObjectName(_fromUtf8("label_k_4"))
        self.horizontalLayout_8.addWidget(self.label_k_4)
        self.label_pic_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_5.setFont(font)
        self.label_pic_5.setAutoFillBackground(False)
        self.label_pic_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_5.setText(_fromUtf8(""))
        self.label_pic_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_5.setWordWrap(False)
        self.label_pic_5.setObjectName(_fromUtf8("label_pic_5"))
        self.horizontalLayout_8.addWidget(self.label_pic_5)
        self.label_pic_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_8.setFont(font)
        self.label_pic_8.setAutoFillBackground(False)
        self.label_pic_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_8.setText(_fromUtf8(""))
        self.label_pic_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_8.setWordWrap(False)
        self.label_pic_8.setObjectName(_fromUtf8("label_pic_8"))
        self.horizontalLayout_8.addWidget(self.label_pic_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.frame_m_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_3.setStyleSheet(_fromUtf8("background-color: rgb(224,224,224);"))
        self.frame_m_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_3.setObjectName(_fromUtf8("frame_m_3"))
        self.gridLayout_13 = QtGui.QGridLayout(self.frame_m_3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_nilaihash = QtGui.QLabel(self.frame_m_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilaihash.setFont(font)
        self.label_nilaihash.setAutoFillBackground(False)
        self.label_nilaihash.setStyleSheet(_fromUtf8(""))
        self.label_nilaihash.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaihash.setText(_fromUtf8(""))
        self.label_nilaihash.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaihash.setWordWrap(False)
        self.label_nilaihash.setObjectName(_fromUtf8("label_nilaihash"))
        self.gridLayout_13.addWidget(self.label_nilaihash, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_m_3)
        self.label_x_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_x_3.setFont(font)
        self.label_x_3.setAutoFillBackground(False)
        self.label_x_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_x_3.setText(_fromUtf8(""))
        self.label_x_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_x_3.setWordWrap(False)
        self.label_x_3.setObjectName(_fromUtf8("label_x_3"))
        self.horizontalLayout_9.addWidget(self.label_x_3)
        self.label_k_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_5.setFont(font)
        self.label_k_5.setAutoFillBackground(False)
        self.label_k_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_5.setText(_fromUtf8(""))
        self.label_k_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_5.setWordWrap(False)
        self.label_k_5.setObjectName(_fromUtf8("label_k_5"))
        self.horizontalLayout_9.addWidget(self.label_k_5)
        self.frame_m_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_4.setStyleSheet(_fromUtf8(""))
        self.frame_m_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_4.setObjectName(_fromUtf8("frame_m_4"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frame_m_4)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.label_nilaip = QtGui.QLabel(self.frame_m_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilaip.setFont(font)
        self.label_nilaip.setAutoFillBackground(False)
        self.label_nilaip.setStyleSheet(_fromUtf8(""))
        self.label_nilaip.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaip.setText(_fromUtf8(""))
        self.label_nilaip.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaip.setWordWrap(False)
        self.label_nilaip.setObjectName(_fromUtf8("label_nilaip"))
        self.gridLayout_14.addWidget(self.label_nilaip, 0, 0, 1, 1)
        self.horizontalLayout_9.addWidget(self.frame_m_4)
        self.label_pic_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_9.setFont(font)
        self.label_pic_9.setAutoFillBackground(False)
        self.label_pic_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_9.setText(_fromUtf8(""))
        self.label_pic_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_9.setWordWrap(False)
        self.label_pic_9.setObjectName(_fromUtf8("label_pic_9"))
        self.horizontalLayout_9.addWidget(self.label_pic_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_0 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_0.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_0.setFont(font)
        self.label_0.setAutoFillBackground(False)
        self.label_0.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_0.setWordWrap(False)
        self.label_0.setObjectName(_fromUtf8("label_0"))
        self.horizontalLayout_10.addWidget(self.label_0)
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setText(_fromUtf8(""))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_10.addWidget(self.label_3)
        self.label_k_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_6.setFont(font)
        self.label_k_6.setAutoFillBackground(False)
        self.label_k_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_6.setText(_fromUtf8(""))
        self.label_k_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_6.setWordWrap(False)
        self.label_k_6.setObjectName(_fromUtf8("label_k_6"))
        self.horizontalLayout_10.addWidget(self.label_k_6)
        self.label_pic_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_11.setFont(font)
        self.label_pic_11.setAutoFillBackground(False)
        self.label_pic_11.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_11.setText(_fromUtf8(""))
        self.label_pic_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_11.setWordWrap(False)
        self.label_pic_11.setObjectName(_fromUtf8("label_pic_11"))
        self.horizontalLayout_10.addWidget(self.label_pic_11)
        self.label_pic_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_10.setFont(font)
        self.label_pic_10.setAutoFillBackground(False)
        self.label_pic_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_10.setText(_fromUtf8(""))
        self.label_pic_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_10.setWordWrap(False)
        self.label_pic_10.setObjectName(_fromUtf8("label_pic_10"))
        self.horizontalLayout_10.addWidget(self.label_pic_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setWordWrap(False)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_12.addWidget(self.label_12)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_12.addWidget(self.label_6)
        self.label_k_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_8.setFont(font)
        self.label_k_8.setAutoFillBackground(False)
        self.label_k_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_8.setText(_fromUtf8(""))
        self.label_k_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_8.setWordWrap(False)
        self.label_k_8.setObjectName(_fromUtf8("label_k_8"))
        self.horizontalLayout_12.addWidget(self.label_k_8)
        self.frame_x_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_x_2.setStyleSheet(_fromUtf8(""))
        self.frame_x_2.setFrameShape(QtGui.QFrame.Box)
        self.frame_x_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_x_2.setObjectName(_fromUtf8("frame_x_2"))
        self.gridLayout_19 = QtGui.QGridLayout(self.frame_x_2)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.label_g = QtGui.QLabel(self.frame_x_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_g.setFont(font)
        self.label_g.setAutoFillBackground(False)
        self.label_g.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_g.setAlignment(QtCore.Qt.AlignCenter)
        self.label_g.setWordWrap(False)
        self.label_g.setObjectName(_fromUtf8("label_g"))
        self.gridLayout_19.addWidget(self.label_g, 0, 0, 1, 1)
        self.horizontalLayout_12.addWidget(self.frame_x_2)
        self.label_q_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_8.setFont(font)
        self.label_q_8.setAutoFillBackground(False)
        self.label_q_8.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_8.setText(_fromUtf8(""))
        self.label_q_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_8.setWordWrap(False)
        self.label_q_8.setObjectName(_fromUtf8("label_q_8"))
        self.horizontalLayout_12.addWidget(self.label_q_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_1.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_1.setFont(font)
        self.label_1.setAutoFillBackground(False)
        self.label_1.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setWordWrap(False)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.horizontalLayout_11.addWidget(self.label_1)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_11.addWidget(self.label_4)
        self.label_k_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_7.setFont(font)
        self.label_k_7.setAutoFillBackground(False)
        self.label_k_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_7.setText(_fromUtf8(""))
        self.label_k_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_7.setWordWrap(False)
        self.label_k_7.setObjectName(_fromUtf8("label_k_7"))
        self.horizontalLayout_11.addWidget(self.label_k_7)
        self.label_pic_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_12.setFont(font)
        self.label_pic_12.setAutoFillBackground(False)
        self.label_pic_12.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_12.setText(_fromUtf8(""))
        self.label_pic_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_12.setWordWrap(False)
        self.label_pic_12.setObjectName(_fromUtf8("label_pic_12"))
        self.horizontalLayout_11.addWidget(self.label_pic_12)
        self.label_q_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_7.setFont(font)
        self.label_q_7.setAutoFillBackground(False)
        self.label_q_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_7.setText(_fromUtf8(""))
        self.label_q_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_7.setWordWrap(False)
        self.label_q_7.setObjectName(_fromUtf8("label_q_7"))
        self.horizontalLayout_11.addWidget(self.label_q_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setWordWrap(False)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_13.addWidget(self.label_10)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_13.addWidget(self.label_7)
        self.label_k_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_9.setFont(font)
        self.label_k_9.setAutoFillBackground(False)
        self.label_k_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_9.setText(_fromUtf8(""))
        self.label_k_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_9.setWordWrap(False)
        self.label_k_9.setObjectName(_fromUtf8("label_k_9"))
        self.horizontalLayout_13.addWidget(self.label_k_9)
        self.frame_m_9 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_9.setStyleSheet(_fromUtf8(""))
        self.frame_m_9.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_9.setObjectName(_fromUtf8("frame_m_9"))
        self.gridLayout_20 = QtGui.QGridLayout(self.frame_m_9)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.label_nilaih = QtGui.QLabel(self.frame_m_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_nilaih.setFont(font)
        self.label_nilaih.setAutoFillBackground(False)
        self.label_nilaih.setStyleSheet(_fromUtf8(""))
        self.label_nilaih.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaih.setText(_fromUtf8(""))
        self.label_nilaih.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaih.setWordWrap(False)
        self.label_nilaih.setObjectName(_fromUtf8("label_nilaih"))
        self.gridLayout_20.addWidget(self.label_nilaih, 0, 0, 1, 1)
        self.horizontalLayout_13.addWidget(self.frame_m_9)
        self.label_q_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_9.setFont(font)
        self.label_q_9.setAutoFillBackground(False)
        self.label_q_9.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_9.setText(_fromUtf8(""))
        self.label_q_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_9.setWordWrap(False)
        self.label_q_9.setObjectName(_fromUtf8("label_q_9"))
        self.horizontalLayout_13.addWidget(self.label_q_9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setWordWrap(False)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_14.addWidget(self.label_11)
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setText(_fromUtf8(""))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_14.addWidget(self.label_8)
        self.label_k_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_10.setFont(font)
        self.label_k_10.setAutoFillBackground(False)
        self.label_k_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_10.setText(_fromUtf8(""))
        self.label_k_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_10.setWordWrap(False)
        self.label_k_10.setObjectName(_fromUtf8("label_k_10"))
        self.horizontalLayout_14.addWidget(self.label_k_10)
        self.label_pic_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_13.setFont(font)
        self.label_pic_13.setAutoFillBackground(False)
        self.label_pic_13.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_13.setText(_fromUtf8(""))
        self.label_pic_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_13.setWordWrap(False)
        self.label_pic_13.setObjectName(_fromUtf8("label_pic_13"))
        self.horizontalLayout_14.addWidget(self.label_pic_13)
        self.label_q_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_10.setFont(font)
        self.label_q_10.setAutoFillBackground(False)
        self.label_q_10.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_10.setText(_fromUtf8(""))
        self.label_q_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_10.setWordWrap(False)
        self.label_q_10.setObjectName(_fromUtf8("label_q_10"))
        self.horizontalLayout_14.addWidget(self.label_q_10)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAutoFillBackground(False)
        self.label_17.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setWordWrap(False)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_15.addWidget(self.label_17)
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setText(_fromUtf8(""))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_15.addWidget(self.label_9)
        self.label_k_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_11.setFont(font)
        self.label_k_11.setAutoFillBackground(False)
        self.label_k_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_11.setText(_fromUtf8(""))
        self.label_k_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_11.setWordWrap(False)
        self.label_k_11.setObjectName(_fromUtf8("label_k_11"))
        self.horizontalLayout_15.addWidget(self.label_k_11)
        self.frame_m_10 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_10.setStyleSheet(_fromUtf8(""))
        self.frame_m_10.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_10.setObjectName(_fromUtf8("frame_m_10"))
        self.gridLayout_21 = QtGui.QGridLayout(self.frame_m_10)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.label_nilaig = QtGui.QLabel(self.frame_m_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilaig.setFont(font)
        self.label_nilaig.setAutoFillBackground(False)
        self.label_nilaig.setStyleSheet(_fromUtf8(""))
        self.label_nilaig.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilaig.setText(_fromUtf8(""))
        self.label_nilaig.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilaig.setWordWrap(False)
        self.label_nilaig.setObjectName(_fromUtf8("label_nilaig"))
        self.gridLayout_21.addWidget(self.label_nilaig, 0, 0, 1, 1)
        self.horizontalLayout_15.addWidget(self.frame_m_10)
        self.label_q_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_11.setFont(font)
        self.label_q_11.setAutoFillBackground(False)
        self.label_q_11.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_11.setText(_fromUtf8(""))
        self.label_q_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_11.setWordWrap(False)
        self.label_q_11.setObjectName(_fromUtf8("label_q_11"))
        self.horizontalLayout_15.addWidget(self.label_q_11)
        self.verticalLayout_3.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setWordWrap(False)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_16.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setText(_fromUtf8(""))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_16.addWidget(self.label_14)
        self.label_pic_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_15.setFont(font)
        self.label_pic_15.setAutoFillBackground(False)
        self.label_pic_15.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_15.setText(_fromUtf8(""))
        self.label_pic_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_15.setWordWrap(False)
        self.label_pic_15.setObjectName(_fromUtf8("label_pic_15"))
        self.horizontalLayout_16.addWidget(self.label_pic_15)
        self.label_pic_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_14.setFont(font)
        self.label_pic_14.setAutoFillBackground(False)
        self.label_pic_14.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_14.setText(_fromUtf8(""))
        self.label_pic_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_14.setWordWrap(False)
        self.label_pic_14.setObjectName(_fromUtf8("label_pic_14"))
        self.horizontalLayout_16.addWidget(self.label_pic_14)
        self.label_q_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_12.setFont(font)
        self.label_q_12.setAutoFillBackground(False)
        self.label_q_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_12.setText(_fromUtf8(""))
        self.label_q_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_12.setWordWrap(False)
        self.label_q_12.setObjectName(_fromUtf8("label_q_12"))
        self.horizontalLayout_16.addWidget(self.label_q_12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAutoFillBackground(False)
        self.label_15.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setWordWrap(False)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_17.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setText(_fromUtf8(""))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_17.addWidget(self.label_16)
        self.frame_x_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_x_3.setStyleSheet(_fromUtf8(""))
        self.frame_x_3.setFrameShape(QtGui.QFrame.Box)
        self.frame_x_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_x_3.setObjectName(_fromUtf8("frame_x_3"))
        self.gridLayout_22 = QtGui.QGridLayout(self.frame_x_3)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.label_r = QtGui.QLabel(self.frame_x_3)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_r.setFont(font)
        self.label_r.setAutoFillBackground(False)
        self.label_r.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_r.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r.setWordWrap(False)
        self.label_r.setObjectName(_fromUtf8("label_r"))
        self.gridLayout_22.addWidget(self.label_r, 0, 0, 1, 1)
        self.horizontalLayout_17.addWidget(self.frame_x_3)
        self.label_k_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_12.setFont(font)
        self.label_k_12.setAutoFillBackground(False)
        self.label_k_12.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_12.setText(_fromUtf8(""))
        self.label_k_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_12.setWordWrap(False)
        self.label_k_12.setObjectName(_fromUtf8("label_k_12"))
        self.horizontalLayout_17.addWidget(self.label_k_12)
        self.label_q_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_13.setFont(font)
        self.label_q_13.setAutoFillBackground(False)
        self.label_q_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_13.setText(_fromUtf8(""))
        self.label_q_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_13.setWordWrap(False)
        self.label_q_13.setObjectName(_fromUtf8("label_q_13"))
        self.horizontalLayout_17.addWidget(self.label_q_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAutoFillBackground(False)
        self.label_18.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setWordWrap(False)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_18.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_19.setText(_fromUtf8(""))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_18.addWidget(self.label_19)
        self.label_pic_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_16.setFont(font)
        self.label_pic_16.setAutoFillBackground(False)
        self.label_pic_16.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_16.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_16.setText(_fromUtf8(""))
        self.label_pic_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_16.setWordWrap(False)
        self.label_pic_16.setObjectName(_fromUtf8("label_pic_16"))
        self.horizontalLayout_18.addWidget(self.label_pic_16)
        self.label_k_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_13.setFont(font)
        self.label_k_13.setAutoFillBackground(False)
        self.label_k_13.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_13.setText(_fromUtf8(""))
        self.label_k_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_13.setWordWrap(False)
        self.label_k_13.setObjectName(_fromUtf8("label_k_13"))
        self.horizontalLayout_18.addWidget(self.label_k_13)
        self.label_q_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_14.setFont(font)
        self.label_q_14.setAutoFillBackground(False)
        self.label_q_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_14.setText(_fromUtf8(""))
        self.label_q_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_14.setWordWrap(False)
        self.label_q_14.setObjectName(_fromUtf8("label_q_14"))
        self.horizontalLayout_18.addWidget(self.label_q_14)
        self.verticalLayout_3.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAutoFillBackground(False)
        self.label_20.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setWordWrap(False)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_19.addWidget(self.label_20)
        self.label_21 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setText(_fromUtf8(""))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_19.addWidget(self.label_21)
        self.frame_m_11 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_11.setStyleSheet(_fromUtf8("background-color: rgb(224,224,224);"))
        self.frame_m_11.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_11.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_11.setObjectName(_fromUtf8("frame_m_11"))
        self.gridLayout_23 = QtGui.QGridLayout(self.frame_m_11)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.label_nilair = QtGui.QLabel(self.frame_m_11)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilair.setFont(font)
        self.label_nilair.setAutoFillBackground(False)
        self.label_nilair.setStyleSheet(_fromUtf8(""))
        self.label_nilair.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilair.setText(_fromUtf8(""))
        self.label_nilair.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilair.setWordWrap(False)
        self.label_nilair.setObjectName(_fromUtf8("label_nilair"))
        self.gridLayout_23.addWidget(self.label_nilair, 0, 0, 1, 1)
        self.horizontalLayout_19.addWidget(self.frame_m_11)
        self.label_k_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_14.setFont(font)
        self.label_k_14.setAutoFillBackground(False)
        self.label_k_14.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_14.setText(_fromUtf8(""))
        self.label_k_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_14.setWordWrap(False)
        self.label_k_14.setObjectName(_fromUtf8("label_k_14"))
        self.horizontalLayout_19.addWidget(self.label_k_14)
        self.label_q_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_15.setFont(font)
        self.label_q_15.setAutoFillBackground(False)
        self.label_q_15.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_15.setText(_fromUtf8(""))
        self.label_q_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_15.setWordWrap(False)
        self.label_q_15.setObjectName(_fromUtf8("label_q_15"))
        self.horizontalLayout_19.addWidget(self.label_q_15)
        self.verticalLayout_3.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_23 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setText(_fromUtf8(""))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_20.addWidget(self.label_23)
        self.label_pic_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_17.setFont(font)
        self.label_pic_17.setAutoFillBackground(False)
        self.label_pic_17.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_17.setText(_fromUtf8(""))
        self.label_pic_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_17.setWordWrap(False)
        self.label_pic_17.setObjectName(_fromUtf8("label_pic_17"))
        self.horizontalLayout_20.addWidget(self.label_pic_17)
        self.label_pic_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_18.setFont(font)
        self.label_pic_18.setAutoFillBackground(False)
        self.label_pic_18.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_18.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_18.setText(_fromUtf8(""))
        self.label_pic_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_18.setWordWrap(False)
        self.label_pic_18.setObjectName(_fromUtf8("label_pic_18"))
        self.horizontalLayout_20.addWidget(self.label_pic_18)
        self.label_22 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAutoFillBackground(False)
        self.label_22.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setWordWrap(False)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_20.addWidget(self.label_22)
        self.label_q_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_16.setFont(font)
        self.label_q_16.setAutoFillBackground(False)
        self.label_q_16.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_16.setText(_fromUtf8(""))
        self.label_q_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_16.setWordWrap(False)
        self.label_q_16.setObjectName(_fromUtf8("label_q_16"))
        self.horizontalLayout_20.addWidget(self.label_q_16)
        self.verticalLayout_3.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_24 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_24.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAutoFillBackground(False)
        self.label_24.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setWordWrap(False)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_21.addWidget(self.label_24)
        self.frame_x_4 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_x_4.setStyleSheet(_fromUtf8("background-color: rgb(158,158,158);\n"
"color: rgb(255, 255, 255);"))
        self.frame_x_4.setFrameShape(QtGui.QFrame.Box)
        self.frame_x_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_x_4.setObjectName(_fromUtf8("frame_x_4"))
        self.gridLayout_24 = QtGui.QGridLayout(self.frame_x_4)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.label_s = QtGui.QLabel(self.frame_x_4)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_s.setFont(font)
        self.label_s.setAutoFillBackground(False)
        self.label_s.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_s.setAlignment(QtCore.Qt.AlignCenter)
        self.label_s.setWordWrap(False)
        self.label_s.setObjectName(_fromUtf8("label_s"))
        self.gridLayout_24.addWidget(self.label_s, 0, 0, 1, 1)
        self.horizontalLayout_21.addWidget(self.frame_x_4)
        self.label_25 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setText(_fromUtf8(""))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_21.addWidget(self.label_25)
        self.label_k_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_15.setFont(font)
        self.label_k_15.setAutoFillBackground(False)
        self.label_k_15.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_15.setText(_fromUtf8(""))
        self.label_k_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_15.setWordWrap(False)
        self.label_k_15.setObjectName(_fromUtf8("label_k_15"))
        self.horizontalLayout_21.addWidget(self.label_k_15)
        self.label_q_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_17.setFont(font)
        self.label_q_17.setAutoFillBackground(False)
        self.label_q_17.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_17.setText(_fromUtf8(""))
        self.label_q_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_17.setWordWrap(False)
        self.label_q_17.setObjectName(_fromUtf8("label_q_17"))
        self.horizontalLayout_21.addWidget(self.label_q_17)
        self.verticalLayout_3.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_26 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_26.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAutoFillBackground(False)
        self.label_26.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setWordWrap(False)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_22.addWidget(self.label_26)
        self.label_pic_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_pic_19.setFont(font)
        self.label_pic_19.setAutoFillBackground(False)
        self.label_pic_19.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_pic_19.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_pic_19.setText(_fromUtf8(""))
        self.label_pic_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic_19.setWordWrap(False)
        self.label_pic_19.setObjectName(_fromUtf8("label_pic_19"))
        self.horizontalLayout_22.addWidget(self.label_pic_19)
        self.label_27 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_27.setText(_fromUtf8(""))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_22.addWidget(self.label_27)
        self.label_k_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_16.setFont(font)
        self.label_k_16.setAutoFillBackground(False)
        self.label_k_16.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_16.setText(_fromUtf8(""))
        self.label_k_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_16.setWordWrap(False)
        self.label_k_16.setObjectName(_fromUtf8("label_k_16"))
        self.horizontalLayout_22.addWidget(self.label_k_16)
        self.label_q_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_18.setFont(font)
        self.label_q_18.setAutoFillBackground(False)
        self.label_q_18.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_18.setText(_fromUtf8(""))
        self.label_q_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_18.setWordWrap(False)
        self.label_q_18.setObjectName(_fromUtf8("label_q_18"))
        self.horizontalLayout_22.addWidget(self.label_q_18)
        self.verticalLayout_3.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_28 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_28.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAutoFillBackground(False)
        self.label_28.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setWordWrap(False)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_23.addWidget(self.label_28)
        self.frame_m_12 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_m_12.setStyleSheet(_fromUtf8(""))
        self.frame_m_12.setFrameShape(QtGui.QFrame.Box)
        self.frame_m_12.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_m_12.setObjectName(_fromUtf8("frame_m_12"))
        self.gridLayout_25 = QtGui.QGridLayout(self.frame_m_12)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.label_nilais = QtGui.QLabel(self.frame_m_12)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_nilais.setFont(font)
        self.label_nilais.setAutoFillBackground(False)
        self.label_nilais.setStyleSheet(_fromUtf8(""))
        self.label_nilais.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_nilais.setText(_fromUtf8(""))
        self.label_nilais.setAlignment(QtCore.Qt.AlignCenter)
        self.label_nilais.setWordWrap(False)
        self.label_nilais.setObjectName(_fromUtf8("label_nilais"))
        self.gridLayout_25.addWidget(self.label_nilais, 0, 0, 1, 1)
        self.horizontalLayout_23.addWidget(self.frame_m_12)
        self.label_29 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_29.setText(_fromUtf8(""))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_23.addWidget(self.label_29)
        self.label_k_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_k_17.setFont(font)
        self.label_k_17.setAutoFillBackground(False)
        self.label_k_17.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_k_17.setText(_fromUtf8(""))
        self.label_k_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k_17.setWordWrap(False)
        self.label_k_17.setObjectName(_fromUtf8("label_k_17"))
        self.horizontalLayout_23.addWidget(self.label_k_17)
        self.label_q_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_q_19.setFont(font)
        self.label_q_19.setAutoFillBackground(False)
        self.label_q_19.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_q_19.setText(_fromUtf8(""))
        self.label_q_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_q_19.setWordWrap(False)
        self.label_q_19.setObjectName(_fromUtf8("label_q_19"))
        self.horizontalLayout_23.addWidget(self.label_q_19)
        self.verticalLayout_3.addLayout(self.horizontalLayout_23)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout_5.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_signing)
        self.frame_output = QtGui.QFrame(self.frame)
        self.frame_output.setMaximumSize(QtCore.QSize(16777215, 200))
        self.frame_output.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_output.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_output.setObjectName(_fromUtf8("frame_output"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_output)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.note = QtGui.QLabel(self.frame_output)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.note.setFont(font)
        self.note.setStyleSheet(_fromUtf8("background-color: rgb(255, 166, 77);\n"
"color: rgb(255, 255, 255);"))
        self.note.setMargin(10)
        self.note.setObjectName(_fromUtf8("note"))
        self.verticalLayout.addWidget(self.note)
        self.isi_note = QtGui.QTextBrowser(self.frame_output)
        self.isi_note.setObjectName(_fromUtf8("isi_note"))
        self.verticalLayout.addWidget(self.isi_note)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.output = QtGui.QLabel(self.frame_output)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setStyleSheet(_fromUtf8("background-color: rgb(255, 166, 77);\n"
"color: rgb(255, 255, 255);"))
        self.output.setMargin(10)
        self.output.setObjectName(_fromUtf8("output"))
        self.verticalLayout_4.addWidget(self.output)
        self.nilai_output = QtGui.QTextBrowser(self.frame_output)
        self.nilai_output.setObjectName(_fromUtf8("nilai_output"))
        self.verticalLayout_4.addWidget(self.nilai_output)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.gridLayout_3.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_output)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.frame_input = QtGui.QFrame(self.frame)
        self.frame_input.setMaximumSize(QtCore.QSize(280, 16777215))
        self.frame_input.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_input.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_input.setObjectName(_fromUtf8("frame_input"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_input)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.label_judul = QtGui.QLabel(self.frame_input)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_judul.setFont(font)
        self.label_judul.setStyleSheet(_fromUtf8("color: rgb(255, 166, 77);"))
        self.label_judul.setAlignment(QtCore.Qt.AlignCenter)
        self.label_judul.setWordWrap(True)
        self.label_judul.setMargin(10)
        self.label_judul.setObjectName(_fromUtf8("label_judul"))
        self.verticalLayout_7.addWidget(self.label_judul)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(0, 15, 0, -1)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.label_30 = QtGui.QLabel(self.frame_input)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_8.addWidget(self.label_30)
        self.label = QtGui.QLabel(self.frame_input)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_8.addWidget(self.label)
        self.label_33 = QtGui.QLabel(self.frame_input)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.verticalLayout_8.addWidget(self.label_33)
        self.label_31 = QtGui.QLabel(self.frame_input)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.verticalLayout_8.addWidget(self.label_31)
        self.label_32 = QtGui.QLabel(self.frame_input)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.verticalLayout_8.addWidget(self.label_32)
        self.label_34 = QtGui.QLabel(self.frame_input)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.verticalLayout_8.addWidget(self.label_34)
        self.verticalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btn_ok = QtGui.QPushButton(self.frame_input)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_ok.sizePolicy().hasHeightForWidth())
        self.btn_ok.setSizePolicy(sizePolicy)
        self.btn_ok.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_ok.setObjectName(_fromUtf8("btn_ok"))
        self.horizontalLayout_2.addWidget(self.btn_ok)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.btn_next = QtGui.QPushButton(self.frame_input)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_next.setFont(font)
        self.btn_next.setCursor(QtGui.QCursor(QtCore.Qt.SizeHorCursor))
        self.btn_next.setText(_fromUtf8(""))
        self.btn_next.setAutoDefault(False)
        self.btn_next.setDefault(False)
        self.btn_next.setFlat(True)
        self.btn_next.setObjectName(_fromUtf8("btn_next"))
        self.horizontalLayout_4.addWidget(self.btn_next)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.frame_input)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 778, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Digital Signature", None))
        self.signing.setText(_translate("MainWindow", "SIGNING", None))
        self.label_m.setText(_translate("MainWindow", "M", None))
        self.label_x.setText(_translate("MainWindow", "x", None))
        self.label_k.setText(_translate("MainWindow", "k", None))
        self.label_p.setText(_translate("MainWindow", "p", None))
        self.label_q.setText(_translate("MainWindow", "q", None))
        self.label_pic.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_pic_2.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_0.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_g.setText(_translate("MainWindow", "g", None))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_r.setText(_translate("MainWindow", "r", None))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_s.setText(_translate("MainWindow", "s", None))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.note.setText(_translate("MainWindow", "NOTE", None))
        self.isi_note.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">=== Nilai s === </span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Salah satu output dari proses signing.</p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Komputasi: </p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">s = (k^-1 (H(M) + xr)) mod q</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>", None))
        self.output.setText(_translate("MainWindow", "OUTPUT", None))
        self.label_judul.setText(_translate("MainWindow", "Mencari Nilai s", None))
        self.label_30.setText(_translate("MainWindow", "Yang Dibutuhkan:", None))
        self.label.setText(_translate("MainWindow", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nilai H(M)</li></ul></body></html>", None))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nilai x</li></ul></body></html>", None))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nilai k</li></ul></body></html>", None))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nilai r</li></ul></body></html>", None))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nilai q</li></ul></body></html>", None))
        self.btn_ok.setText(_translate("MainWindow", "OK", None))



